[package]
name = "museair"
version = "0.2.0"
edition = "2021"
authors = ["K--Aethiax"]
publish = true

description = "New fastest portable hash: immune to blinding multiplication, even faster then wyhash, SMHasher3 passed."

documentation = "https://docs.rs/museair"
repository = "https://github.com/eternal-io/museair"
license = "MIT OR Apache-2.0"
readme = "CRATES.IO-README.md"

keywords = ["hash", "hasher", "museair"]
categories = ["algorithms", "no-std"]

exclude = ["smhasher*", "results/*", "*.cpp", "*.md", "!CRATES.IO-README.md"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dev-dependencies]
criterion = "0.5.1"
komihash = "0.4.1"
wyhash-final4 = "0.1.3"
wyhash = "0.5.0"


[[bench]]
name = "hashes"
harness = false
