[package]
name = "museair"
version = "0.3.0-rc6"
edition = "2021"
authors = ["K--Aethiax"]
publish = true

description = "Blazingly™ fast portable hash function designed by K--Aethiax."

documentation = "https://docs.rs/museair"
repository = "https://github.com/eternal-io/museair"
license = "MIT OR Apache-2.0"
readme = "CRATES.IO-README.md"

keywords = ["hash", "hasher", "museair"]
categories = ["algorithms", "no-std"]

exclude = ["smhasher*", "results/*", "*.cpp", "*.md", "!CRATES.IO-README.md"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dev-dependencies]
hashverify = "0.1.0"
criterion = "0.5.1"
komihash = "0.4.1"
wyhash-final4 = "0.2.1"
wyhash = "0.5.0"


[[bench]]
name = "hashes"
harness = false
